import { VideoSettingData } from "../config/ConfigData";
export interface ICameraViewRenderer {
    facing: string;
    readonly frame: number;
    getFrame: () => number;
    height: number;
    width: number;
    readonly image: ImageData;
    getImage: () => ImageData;
    initialize: (videoSettings: VideoSettingData) => Promise<boolean>;
    destroy: () => void;
    readonly rotated?: boolean;
}
export declare class CameraViewRenderer implements ICameraViewRenderer {
    private canvas_process;
    private context_process;
    _video: HTMLVideoElement;
    private _facing;
    private vw;
    private vh;
    private w;
    private h;
    private pw;
    private ph;
    private ox;
    private oy;
    private rotatePortrait;
    private rot;
    private target;
    private targetFrameRate;
    private imageDataCache;
    private _frame;
    private lastCache;
    private videoResizeListener;
    constructor(video: HTMLVideoElement);
    get facing(): string;
    get height(): number;
    get width(): number;
    get video(): HTMLVideoElement;
    get frame(): number;
    get canvasProcess(): HTMLCanvasElement;
    get contextProcess(): CanvasRenderingContext2D;
    get rotated(): boolean;
    getFrame(): number;
    getImage(): ImageData;
    get image(): ImageData;
    private drawFrame;
    prepareImage(): void;
    private onVideoResize;
    private openCameraStream;
    private getVideoDevices;
    private findCamera;
    initialize(videoSettings: VideoSettingData): Promise<boolean>;
    destroy(): void;
}
